APP  = axpy_offload
SRCS = src/axpy_offload.c
# It is sufficient to tell the build system that we want to build 
# a heterogeneous executable by setting `INCL_DEVICE_BINARY` to `true`, 
# and it will automatically look for the Snitch application with the same name as CVA6's.
INCL_DEVICE_BINARY = true

include ../common.mk